name: cocukla
description: Hayatı cocuklarla yaşayın.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


version: 2.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  splashscreen: ^1.2.0
  flutter_rating_bar: ^1.2.0
  google_maps_flutter:
  geolocator: ^5.0.0
  flutter_swiper: ^1.1.6
  cloud_firestore:
  firebase_auth: ^0.14.0
  firebase_storage:
  firebase_messaging:
  google_sign_in:
  flutter_facebook_login: ^2.0.1
  http:
  uuid:
  image_picker:
  cached_network_image:
  rflutter_alert:
  url_launcher:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  image_path: "assets/images/cocukla_launcher.png"
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Medium.otf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.otf
        - asset: assets/fonts/montserrat/Montserrat-Bold.otf
    - family: Kristen
      fonts:
        - asset: assets/fonts/Kristen.ttf

    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.otf

    - family: MontserratLight
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.otf
