import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class ComponentTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Container(
          child: ListView(
            children: <Widget>[
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
              Text("dfgx xbx xv xbxvbxbvc xcvb vxcb xcb xcvbxvcb"),
            ],
          ),
        )
      ),
    );
  }
}
